### ISSUE TITLE
Sorry for the off topic

### ISSUE THREAD

**Issue by Zornthimmberglobber** [minchingtonak/dots#2]
Hey man sorry for the off topic but are there any updates on basil? Also how can I get involved I would like to help out in any way I can

**Comment by minchingtonak** [comment]
Hey! I believe neither me nor the person I worked on basil with are still working on it. If you have some ideas for improving basil, I encourage you to [fork the project](https://github.com/basilTeam/basil) and go from there.

And if you have technical questions I would recommend reaching out to the other author, elucent, who probably remembers more about it than I do at this point.
